;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-colon
	keyboard-escape-quit
	kill-region
	))

(setq mc/cmds-to-run-once
      '(
	isearch-backward-regexp
	isearch-other-control-char
	suspend-frame
	))
